version: "3"

services:
  auto-test:
    build: .
    container_name: test_auto
    networks:
      - test_network
    volumes:
      - ./:/app
      - /opt/api_automation_allure:/app/allure-results

    command: python main.py
    restart: "no"

networks:
  test_network:
    external: true