version: "3"

services:
  auto-test:
    build: .
    container_name: test_auto
    networks:
      - test_network
    volumes:
      - ./:/app
      - /opt/api_automation_test:/app/allure-report

    command: python main.py

networks:
  test_network:
    external: true